---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - metastore.nineinfra.tech
  resources:
  - metastoreclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metastore.nineinfra.tech
  resources:
  - metastoreclusters/finalizers
  verbs:
  - update
- apiGroups:
  - metastore.nineinfra.tech
  resources:
  - metastoreclusters/status
  verbs:
  - get
  - patch
  - update
